version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: fct_orders
    columns:
      - name: order_id
        tests: [not_null, unique]

      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
